package model;
// Generated Apr 12, 2021 7:24:33 PM by Hibernate Tools 4.3.1



/**
 * Shares generated by hbm2java
 */
public class Shares  implements java.io.Serializable {


     private Integer id;
     private int idUsers;
     private int idVideos;
     private String email;
     private Integer time;

    public Shares() {
    }

	
    public Shares(int idUsers, int idVideos) {
        this.idUsers = idUsers;
        this.idVideos = idVideos;
    }
    public Shares(int idUsers, int idVideos, String email, Integer time) {
       this.idUsers = idUsers;
       this.idVideos = idVideos;
       this.email = email;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdUsers() {
        return this.idUsers;
    }
    
    public void setIdUsers(int idUsers) {
        this.idUsers = idUsers;
    }
    public int getIdVideos() {
        return this.idVideos;
    }
    
    public void setIdVideos(int idVideos) {
        this.idVideos = idVideos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getTime() {
        return this.time;
    }
    
    public void setTime(Integer time) {
        this.time = time;
    }




}


